package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * CheckInfo generated by hbm2java
 */
public class CheckInfo implements java.io.Serializable {

	private int id;
	private Integer checkId;
	private Integer stuId;
	private Integer state;

	public CheckInfo() {
	}

	public CheckInfo(int id) {
		this.id = id;
	}

	public CheckInfo(int id, Integer checkId, Integer stuId, Integer state) {
		this.id = id;
		this.checkId = checkId;
		this.stuId = stuId;
		this.state = state;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCheckId() {
		return this.checkId;
	}

	public void setCheckId(Integer checkId) {
		this.checkId = checkId;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
