package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Check generated by hbm2java
 */
public class Check implements java.io.Serializable {

	private int id;
	private int curId;
	private Date checkDate;

	public Check() {
	}

	public Check(int id, int curId) {
		this.id = id;
		this.curId = curId;
	}

	public Check(int id, int curId, Date checkDate) {
		this.id = id;
		this.curId = curId;
		this.checkDate = checkDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCurId() {
		return this.curId;
	}

	public void setCurId(int curId) {
		this.curId = curId;
	}

	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

}
