package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * CourseExam generated by hbm2java
 */
public class CourseExam implements java.io.Serializable {

	private Integer id;
	private Integer stuId;
	private Integer curId;
	private Double examScore;

	public CourseExam() {
	}

	public CourseExam(Integer stuId, Integer curId, Double examScore) {
		this.stuId = stuId;
		this.curId = curId;
		this.examScore = examScore;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Integer getCurId() {
		return this.curId;
	}

	public void setCurId(Integer curId) {
		this.curId = curId;
	}

	public Double getExamScore() {
		return this.examScore;
	}

	public void setExamScore(Double examScore) {
		this.examScore = examScore;
	}

}
