package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int curId;
	private String curName;
	private int teaId;
	private String curIntroduction;

	public Course() {
	}

	public Course(int curId, String curName, int teaId, String curIntroduction) {
		this.curId = curId;
		this.curName = curName;
		this.teaId = teaId;
		this.curIntroduction = curIntroduction;
	}

	public int getCurId() {
		return this.curId;
	}

	public void setCurId(int curId) {
		this.curId = curId;
	}

	public String getCurName() {
		return this.curName;
	}

	public void setCurName(String curName) {
		this.curName = curName;
	}

	public int getTeaId() {
		return this.teaId;
	}

	public void setTeaId(int teaId) {
		this.teaId = teaId;
	}

	public String getCurIntroduction() {
		return this.curIntroduction;
	}

	public void setCurIntroduction(String curIntroduction) {
		this.curIntroduction = curIntroduction;
	}

}
