package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int stuId;
	private Integer stuAge;
	private String stuName;
	private String stuSex;
	private String stuMajor;
	private String stuClass;

	public Student() {
	}

	public Student(int stuId, String stuName, String stuSex, String stuMajor, String stuClass) {
		this.stuId = stuId;
		this.stuName = stuName;
		this.stuSex = stuSex;
		this.stuMajor = stuMajor;
		this.stuClass = stuClass;
	}

	public Student(int stuId, Integer stuAge, String stuName, String stuSex, String stuMajor, String stuClass) {
		this.stuId = stuId;
		this.stuAge = stuAge;
		this.stuName = stuName;
		this.stuSex = stuSex;
		this.stuMajor = stuMajor;
		this.stuClass = stuClass;
	}

	public int getStuId() {
		return this.stuId;
	}

	public void setStuId(int stuId) {
		this.stuId = stuId;
	}

	public Integer getStuAge() {
		return this.stuAge;
	}

	public void setStuAge(Integer stuAge) {
		this.stuAge = stuAge;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public String getStuSex() {
		return this.stuSex;
	}

	public void setStuSex(String stuSex) {
		this.stuSex = stuSex;
	}

	public String getStuMajor() {
		return this.stuMajor;
	}

	public void setStuMajor(String stuMajor) {
		this.stuMajor = stuMajor;
	}

	public String getStuClass() {
		return this.stuClass;
	}

	public void setStuClass(String stuClass) {
		this.stuClass = stuClass;
	}

}
