package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * StudentChoiceCourse generated by hbm2java
 */
public class StudentChoiceCourse implements java.io.Serializable {

	private Integer id;
	private Integer curId;
	private Integer stuId;
	private Double examScore;
	private Double taskScore;
	private Double nomalScore;
	private Double totalGrade;

	public StudentChoiceCourse() {
	}

	public StudentChoiceCourse(Integer curId, Integer stuId, Double examScore, Double taskScore, Double nomalScore,
			Double totalGrade) {
		this.curId = curId;
		this.stuId = stuId;
		this.examScore = examScore;
		this.taskScore = taskScore;
		this.nomalScore = nomalScore;
		this.totalGrade = totalGrade;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCurId() {
		return this.curId;
	}

	public void setCurId(Integer curId) {
		this.curId = curId;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Double getExamScore() {
		return this.examScore;
	}

	public void setExamScore(Double examScore) {
		this.examScore = examScore;
	}

	public Double getTaskScore() {
		return this.taskScore;
	}

	public void setTaskScore(Double taskScore) {
		this.taskScore = taskScore;
	}

	public Double getNomalScore() {
		return this.nomalScore;
	}

	public void setNomalScore(Double nomalScore) {
		this.nomalScore = nomalScore;
	}

	public Double getTotalGrade() {
		return this.totalGrade;
	}

	public void setTotalGrade(Double totalGrade) {
		this.totalGrade = totalGrade;
	}

}
