package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * TaskGrade generated by hbm2java
 */
public class TaskGrade implements java.io.Serializable {

	private Integer id;
	private Integer taskId;
	private Integer curId;
	private Integer stuId;
	private Double taskScore;

	public TaskGrade() {
	}

	public TaskGrade(Integer taskId, Integer curId, Integer stuId, Double taskScore) {
		this.taskId = taskId;
		this.curId = curId;
		this.stuId = stuId;
		this.taskScore = taskScore;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getCurId() {
		return this.curId;
	}

	public void setCurId(Integer curId) {
		this.curId = curId;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Double getTaskScore() {
		return this.taskScore;
	}

	public void setTaskScore(Double taskScore) {
		this.taskScore = taskScore;
	}

}
