package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private Integer id;
	private String taskName;
	private Date taskDate;
	private String taskContent;

	public Task() {
	}

	public Task(String taskName) {
		this.taskName = taskName;
	}

	public Task(String taskName, Date taskDate, String taskContent) {
		this.taskName = taskName;
		this.taskDate = taskDate;
		this.taskContent = taskContent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public Date getTaskDate() {
		return this.taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
	}

	public String getTaskContent() {
		return this.taskContent;
	}

	public void setTaskContent(String taskContent) {
		this.taskContent = taskContent;
	}

}
