package cn.edu.zucc.stumanager.databean;
// Generated 2018-5-22 21:15:08 by Hibernate Tools 5.1.7.Final

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private int teaId;
	private Integer teaAge;
	private String teaName;
	private String teaSex;

	public Teacher() {
	}

	public Teacher(int teaId, String teaName, String teaSex) {
		this.teaId = teaId;
		this.teaName = teaName;
		this.teaSex = teaSex;
	}

	public Teacher(int teaId, Integer teaAge, String teaName, String teaSex) {
		this.teaId = teaId;
		this.teaAge = teaAge;
		this.teaName = teaName;
		this.teaSex = teaSex;
	}

	public int getTeaId() {
		return this.teaId;
	}

	public void setTeaId(int teaId) {
		this.teaId = teaId;
	}

	public Integer getTeaAge() {
		return this.teaAge;
	}

	public void setTeaAge(Integer teaAge) {
		this.teaAge = teaAge;
	}

	public String getTeaName() {
		return this.teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	public String getTeaSex() {
		return this.teaSex;
	}

	public void setTeaSex(String teaSex) {
		this.teaSex = teaSex;
	}

}
